@startuml architecture

frame "Context" {
  [actions]
  [reducer]
}

frame "Component" {
  [Root] <<jsx>>
  [Children] <<jsx>>
  [Combine] <<jsx>>
}

Root *-- "1..1" Combine
Combine *-- "1..*" Children

reducer <.. actions

Combine *- "1..*" reducer
Combine *- "1..*" actions

Children .> actions

@enduml
